[package]
name = "stream-unpack"
description = "A small library for stream unpacking archives"
version = "1.2.0"
authors = ["mkrsym1 <mkrsym1@gmail.com>"]
repository = "https://github.com/mkrsym1/stream-unpack"
license = "GPL-3.0"
edition = "2021"

[dependencies]
thiserror = "1"
anyhow = "1"

byteorder = "1.5"

inflate = { version = "0.4", optional = true }

aes = { version = "0.9", optional = true }
pbkdf2 = { version = "0.13", optional = true }
sha1 = { version = "0.11", optional = true }

[features]
default = [ "zip", "deflate" ]

# ZIP
zip = []
zip-comments = [ "zip" ]

# Decompressors
deflate = [ "dep:inflate" ]

# Decryptors
zipcrypto = []
ae-x = [ "dep:aes", "dep:pbkdf2", "dep:sha1" ]
